// VSOP87A series evaluator — heliocentric rectangular coordinates in the theory's own frame
// (dynamical ecliptic and equinox J2000; rotate with frames.js `vsopToEcliptic` for the scene frame).
//
// Source: Bretagnon & Francou 1988, A&A 202, 309; vsop87.doc from https://ftp.imcce.fr/pub/ephem/planets/vsop87/:
//   "(2)  T**alpha * A * cos(B+CT)   where T: time expressed in Thousands of Julian Years (tjy) elapsed from
//    J2000 (JD2451545.0); alpha: degree of time in-between 0 and 5 … apply for each term the formulae (1) or (2)
//    with T=(JD-2451545)/365250, add up the terms so computed for every one coordinate."
//   A in au/tjy^alpha, B in radians, C in rad/tjy.
// Velocity (vsop87.f): dX/dT = Σ_α [ α T^(α−1) Σ A cos u − T^α Σ A C sin u ], u = B + C T, then ÷ 365250 → au/day.
// The α·T^(α−1) term is evaluated only for α ≥ 1 so that T = 0 (JD 2451545.0 exactly) never forms 0 · ∞.
//
// Data layout (src/astro/data/vsop87a.js, generated by scripts/build-vsop87.mjs):
//   SERIES[body][coord] = array indexed by power α of flat arrays [A0, B0, C0, A1, B1, C1, …], each sorted by |A|
//   descending; a body may have fewer than 6 powers (Uranus and Neptune have no T⁵ and their Z has no T⁴).
import { J2000, DAYS_PER_TJY } from './constants.js';

/** The eight planets in VSOP87 body-code order (1…8). */
export const BODY_KEYS = ['mercury', 'venus', 'earth', 'mars', 'jupiter', 'saturn', 'uranus', 'neptune'];

/** Coordinate keys in VSOP87A "ic" order (1 = X, 2 = Y, 3 = Z). */
export const COORD_KEYS = ['x', 'y', 'z'];

/**
 * Amplitude threshold of the 'display' tier: the prefix of each |A|-sorted series with |A| ≥ 1e-7 AU
 * (plan §Decisions 2; measured max error ≈ 436 km for Uranus over 1900–2100, stored in META.measuredBounds).
 */
export const DISPLAY_CUTOFF_AU = 1e-7;

const POS_KEYS = ['x', 'y', 'z'];
const VEL_KEYS = ['vx', 'vy', 'vz'];
const DEFAULT_OPTS = Object.freeze({ tier: 'full', velocity: true });

/**
 * @typedef {{x:number, y:number, z:number, vx:number, vy:number, vz:number}} RawState
 *   Heliocentric position (AU) and velocity (AU/day) in the VSOP87A dynamical ecliptic J2000 frame.
 */

/**
 * Number of leading terms of an |A|-sorted flat [A,B,C,…] array with |A| ≥ `cutoff` (the display prefix).
 * @param {ArrayLike<number>} flat @param {number} cutoff @returns {number}
 */
export function prefixCount(flat, cutoff) {
  let n = 0;
  for (let i = 0; i < flat.length; i += 3) {
    if (Math.abs(flat[i]) < cutoff) break;
    n++;
  }
  return n;
}

/**
 * Compile a SERIES object into typed arrays and return an allocation-free evaluator.
 * @param {Record<string, {x:number[][], y:number[][], z:number[][]}>} SERIES data module export
 * @param {{displayCounts?: Record<string, {x:number[], y:number[], z:number[]}>}} [meta] optional META; when
 *   `meta.displayCounts` is present it defines the display tier, otherwise the prefix with |A| ≥ DISPLAY_CUTOFF_AU
 * @returns {{
 *   evalRaw: (body: string, jdTdb: number, opts?: {tier?: 'full'|'display', velocity?: boolean}, out?: RawState) => RawState,
 *   bodies: string[],
 *   termCount: (body: string, tier?: 'full'|'display') => number,
 *   displayCounts: Record<string, {x:number[], y:number[], z:number[]}>,
 * }}
 */
export function createEvaluator(SERIES, meta) {
  /** @type {Record<string, {terms: Float64Array[], nFull: number[], nDisplay: number[]}[]>} */
  const compiled = {};
  /** @type {Record<string, {x:number[], y:number[], z:number[]}>} */
  const displayCounts = {};
  const bodies = Object.keys(SERIES);

  for (const body of bodies) {
    const src = SERIES[body];
    const perCoord = [];
    const dc = { x: [], y: [], z: [] };
    for (let ic = 0; ic < 3; ic++) {
      const key = COORD_KEYS[ic];
      const powers = src[key] ?? [];
      const terms = [];
      const nFull = [];
      const nDisplay = [];
      const metaCounts = meta?.displayCounts?.[body]?.[key];
      for (let a = 0; a < powers.length; a++) {
        const flat = powers[a] ?? [];
        if (flat.length % 3 !== 0) throw new RangeError(`${body}.${key}[${a}]: flat array length ${flat.length} is not a multiple of 3`);
        const arr = Float64Array.from(flat);
        const n = arr.length / 3;
        const nd = metaCounts?.[a] !== undefined ? Math.min(metaCounts[a], n) : prefixCount(arr, DISPLAY_CUTOFF_AU);
        terms.push(arr);
        nFull.push(n);
        nDisplay.push(nd);
        dc[key].push(nd);
      }
      perCoord.push({ terms, nFull, nDisplay });
    }
    compiled[body] = perCoord;
    displayCounts[body] = dc;
  }

  /**
   * Evaluate one body. Allocation-free when `out` is supplied.
   * @param {string} body one of BODY_KEYS
   * @param {number} jdTdb Julian date (TDB; TT is within 2 ms)
   * @param {{tier?: 'full'|'display', velocity?: boolean}} [opts] default {tier:'full', velocity:true}
   * @param {RawState} [out] target object; when `opts.velocity` is false vx/vy/vz are left untouched
   * @returns {RawState}
   */
  function evalRaw(body, jdTdb, opts = DEFAULT_OPTS, out = { x: 0, y: 0, z: 0, vx: 0, vy: 0, vz: 0 }) {
    const cb = compiled[body];
    if (cb === undefined) throw new RangeError(`vsop87: unknown body '${body}'`);
    const tier = opts.tier ?? 'full';
    if (tier !== 'full' && tier !== 'display') throw new RangeError(`vsop87: unknown tier '${tier}'`);
    const display = tier === 'display';
    const velocity = opts.velocity !== false;
    const T = (jdTdb - J2000) / DAYS_PER_TJY; // thousands of Julian years from J2000 (vsop87.doc)

    for (let ic = 0; ic < 3; ic++) {
      const cc = cb[ic];
      const powers = cc.terms;
      const counts = display ? cc.nDisplay : cc.nFull;
      let pos = 0; // Σ_α T^α Σ A cos u
      let vel = 0; // dX/dT in AU/tjy
      let Tp = 1; // T^α
      let TpPrev = 0; // T^(α−1), only used for α ≥ 1
      for (let a = 0; a < powers.length; a++) {
        const arr = powers[a];
        const n3 = counts[a] * 3;
        let sc = 0; // Σ A cos u
        let ss = 0; // Σ A C sin u
        if (velocity) {
          for (let i = 0; i < n3; i += 3) {
            const A = arr[i], C = arr[i + 2];
            const u = arr[i + 1] + C * T;
            sc += A * Math.cos(u);
            ss += A * C * Math.sin(u);
          }
        } else {
          for (let i = 0; i < n3; i += 3) {
            sc += arr[i] * Math.cos(arr[i + 1] + arr[i + 2] * T);
          }
        }
        pos += Tp * sc;
        if (velocity) {
          vel -= Tp * ss;
          if (a >= 1) vel += a * TpPrev * sc; // α T^(α−1) Σ A cos u — only for α ≥ 1 (finite at T = 0)
        }
        TpPrev = Tp;
        Tp *= T;
      }
      out[POS_KEYS[ic]] = pos;
      if (velocity) out[VEL_KEYS[ic]] = vel / DAYS_PER_TJY; // AU/tjy → AU/day (vsop87.f: r(i)=r(i)/a1000)
    }
    return out;
  }

  /**
   * @param {string} body @param {'full'|'display'} [tier]
   * @returns {number} number of terms evaluated for that body and tier (all three coordinates)
   */
  function termCount(body, tier = 'full') {
    const cb = compiled[body];
    if (cb === undefined) throw new RangeError(`vsop87: unknown body '${body}'`);
    let n = 0;
    for (let ic = 0; ic < 3; ic++) {
      const counts = tier === 'display' ? cb[ic].nDisplay : cb[ic].nFull;
      for (let a = 0; a < counts.length; a++) n += counts[a];
    }
    return n;
  }

  return { evalRaw, bodies, termCount, displayCounts };
}
